### ISSUE TITLE
diopi_test在生成算子测试数据时有部分算子的output data生成报错

### ISSUE THREAD

**Issue by jianc59399** [DeepLink-org/DIOPI#1362]
**Describe the bug**
**运行python main.py --mode gen_data --fname all_ops，报如下错误：**
Traceback (most recent call last):
  File "/data/jc_test/DIOPI/diopi_test/python/main.py", line 160, in <module>
    inp_items, outp_items = gen_data(args.model_name.lower(), cache_path,
  File "/data/jc_test/DIOPI/diopi_test/python/conformance/gen_data.py", line 43, in gen_data
    raise GenDataFailedException(f"Data generation failed, with {GenInputData.err_case_counter} input case failures and {GenOutputData.err_case_counter} output case failures.")
conformance.exception.GenDataFailedException: Data generation failed, with 0 input case failures and 71 output case failures.
部分算子的output data生成报错，导致全算子测试时很多测试用例无法通过。torch版本2.4.0，cuda为11.8.请问是什么原因呢？谢谢。

**Additional context**
gen_output.py报错：
2024-12-23 17:19:04,520 - ConformanceTest - gen_output.py - 67 - ERROR - Generate output data for diopi_functions.hardtanh [hardtanh::hardtanh_25.pth] failed, cause by 
min_val cannot be greater than max_val
2024-12-23 17:19:04,521 - ConformanceTest - gen_output.py - 67 - ERROR - Generate output data for diopi_functions.hardtanh [hardtanh::hardtanh_26.pth] failed, cause by 
min_val cannot be greater than max_val
2024-12-23 17:19:04,521 - ConformanceTest - gen_output.py - 67 - ERROR - Generate output data for diopi_functions.hardtanh [hardtanh_int::hardtanh_2.pth] failed, cause by 
min_val cannot be greater than max_val
2024-12-23 17:19:04,526 - ConformanceTest - gen_output.py - 67 - ERROR - Generate output data for diopi_functions.hardtanh [hardtanh_int::hardtanh_7.pth] failed, cause by 
min_val cannot be greater than max_val
2024-12-23 17:19:04,526 - ConformanceTest - gen_output.py - 67 - ERROR - Generate output data for diopi_functions.hardtanh [hardtanh_int::hardtanh_8.pth] failed, cause by 
min_val cannot be greater than max_val

2024-12-23 14:24:53,204 - ConformanceTest - gen_output.py - 66 - ERROR - Generate output data for diopi_functions.adadelta [adadelta::adadelta_6.pth] failed, cause by 
adadelta() missing 1 required positional argument: 'state_steps'
2024-12-23 14:24:53,204 - ConformanceTest - gen_output.py - 66 - ERROR - Generate output data for diopi_functions.adadelta [adadelta::adadelta_7.pth] failed, cause by 
adadelta() missing 1 required positional argument: 'state_steps'

2024-12-23 14:24:53,211 - ConformanceTest - gen_output.py - 66 - ERROR - Generate output data for diopi_functions.rmsprop [rmsprop::rmsprop_21.pth] failed, cause by 
rmsprop() missing 1 required positional argument: 'state_steps'
2024-12-23 14:24:53,211 - ConformanceTest - gen_output.py - 66 - ERROR - Generate output data for diopi_functions.rmsprop [rmsprop::rmsprop_22.pth] failed, cause by 
rmsprop() missing 1 required positional argument: 'state_steps'
2024-12-23 14:24:53,211 - ConformanceTest - gen_output.py - 66 - ERROR - Generate output data for diopi_functions.rmsprop [rmsprop::rmsprop_23.pth] failed, cause by 
rmsprop() missing 1 required positional argument: 'state_steps'

**Comment by caikun-pjlab** [comment]
您好，推荐使用 torch 2.1
